version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vxr
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # TODO: Change to `./db/sql:/docker-entrypoint-initdb.d` after changing wsl.conf
      # See: https://qiita.com/taiba/items/02e2248111c1cc7efe93
      - ./db/sql/001-create-tables.sql:/docker-entrypoint-initdb.d/001-create-tables.sql
      - ./db/sql/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 3306:3306
